# Generated by Django 5.0.6 on 2024-05-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='money',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
