# Generated by Django 5.0.6 on 2024-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_users_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
